# logging.yml
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(message)s"
    json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    
    json_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: json
        stream: ext://sys.stdout
    
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: .data/info.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: .data/errors.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

loggers:
    uvicorn:
        level: INFO
        handlers: [console]
        propagate: no
    
    uvicorn.error:
        level: DEBUG
        handlers: [console]
        propagate: no
    
    gunicorn:
        level: INFO
        handlers: [console]
        propagate: no
    
    app:  # Your application logs
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no
    
    app.estimate:  # Specific logger for estimate.py
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console]